lib/parkin_web/router.ex
defmodule ParkinWeb.Router do
  use ParkinWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Parkin.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/parkings", ParkingController, only: [:index, :new, :create, :show]
  end

  scope "/", ParkinWeb do
    pipe_through :browser
    resources "/sessions", SessionController, only: [:new, :create]
    get "/parking/search", ParkingsearchController, :search
    post "/parking/summary", ParkingsearchController, :summary
    get "/parking/summary/:placename", ParkingsearchController, :summary_details

    resources "/parking_slots", ParkingSlotController
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index
  end

  # scope "/", ParkinWeb do
  #   pipe_through [:browser, :browser_auth, :ensure_auth]
  #   resources "/orders", OrderController, only: [:index, :create, :show]
  # end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/payments", PaymentController, only: [:index, :new, :create, :show]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth]

    resources "/users", UserController, only: [:new, :create]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]

    resources "/users", UserController, only: [:index, :show, :edit, :update, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ParkinWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ParkinWeb.Telemetry
    end
  end
end

lib/parkin_web/views/layout_view.ex
defmodule ParkinWeb.LayoutView do
  use ParkinWeb, :view
end

lib/parkin_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Parkin · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>

  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ol class="breadcrumb pull-right">
            <%= if Parkin.Authentication.load_current_user(@conn) do %>
                <li>Hello <%= Parkin.Authentication.load_current_user(@conn).username %></li>
                <li><%= link "Log out", to: Routes.session_path(@conn, :delete, Parkin.Authentication.load_current_user(@conn)), method: "delete" %></li>
            <% else %>
            <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
            <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
            <% end %>
          </ol>
        <span class="logo"></span>
        </nav>

        <h3 style="color: #4b8cd6">ParkIn - Tartu! Parking solutions for the Digital Generation</h3>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>