lib/parkin_web/router.ex
defmodule ParkinWeb.Router do
  use ParkinWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Parkin.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/parkings", ParkingController, only: [:index, :new, :create, :show]
  end

  scope "/", ParkinWeb do
    pipe_through :browser
    resources "/sessions", SessionController, only: [:new, :create]
    get "/parking/search", ParkingsearchController, :search
    post "/parking/summary", ParkingsearchController, :summary
    get "/parking/summary/:placename", ParkingsearchController, :summary_details

    resources "/parking_slots", ParkingSlotController
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index
  end

  # scope "/", ParkinWeb do
  #   pipe_through [:browser, :browser_auth, :ensure_auth]
  #   resources "/orders", OrderController, only: [:index, :create, :show]
  # end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]
    resources "/payments", PaymentController, only: [:index, :new, :create, :show]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth]

    resources "/users", UserController, only: [:new, :create]
  end

  scope "/", ParkinWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]

    resources "/users", UserController, only: [:index, :show, :edit, :update, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", ParkinWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: ParkinWeb.Telemetry
    end
  end
end

lib/parkin/parking_search.ex
defmodule Parkin.ParkingSearch do
  @moduledoc """
  The ParkingSearch context.
  """

  import Ecto.Query, warn: false
  alias Parkin.Repo

  alias Parkin.ParkingSearch.ParkingSlot

  @doc """
  Returns the list of parking_slots.

  ## Examples

      iex> list_parking_slots()
      [%ParkingSlot{}, ...]

  """
  def list_parking_slots do
    Repo.all(ParkingSlot)
  end

  @doc """
  Gets a single parking_slot.

  Raises `Ecto.NoResultsError` if the Parking slot does not exist.

  ## Examples

      iex> get_parking_slot!(123)
      %ParkingSlot{}

      iex> get_parking_slot!(456)
      ** (Ecto.NoResultsError)

  """
  def get_parking_slot!(id), do: Repo.get!(ParkingSlot, id)

  @doc """
  Creates a parking_slot.

  ## Examples

      iex> create_parking_slot(%{field: value})
      {:ok, %ParkingSlot{}}

      iex> create_parking_slot(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_parking_slot(attrs \\ %{}) do
    %ParkingSlot{}
    |> ParkingSlot.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a parking_slot.

  ## Examples

      iex> update_parking_slot(parking_slot, %{field: new_value})
      {:ok, %ParkingSlot{}}

      iex> update_parking_slot(parking_slot, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_parking_slot(%ParkingSlot{} = parking_slot, attrs) do
    parking_slot
    |> ParkingSlot.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a parking_slot.

  ## Examples

      iex> delete_parking_slot(parking_slot)
      {:ok, %ParkingSlot{}}

      iex> delete_parking_slot(parking_slot)
      {:error, %Ecto.Changeset{}}

  """
  def delete_parking_slot(%ParkingSlot{} = parking_slot) do
    Repo.delete(parking_slot)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking parking_slot changes.

  ## Examples

      iex> change_parking_slot(parking_slot)
      %Ecto.Changeset{data: %ParkingSlot{}}

  """
  def change_parking_slot(%ParkingSlot{} = parking_slot, attrs \\ %{}) do
    ParkingSlot.changeset(parking_slot, attrs)
  end
end

lib/parkin/parking_search/parking_slot.ex
defmodule Parkin.ParkingSearch.ParkingSlot do
  use Ecto.Schema
  import Ecto.Changeset

  schema "parking_slots" do
    field :available_slots, :integer
    field :reserved_slots, :integer
    field :loc_lat_long, :string
    field :parking_place, :string
    field :total_slots, :integer
    field :zone, :string
    field :lock, :integer
    field :slot_buffer, :integer

    timestamps()
  end

  @doc false
  def changeset(parking_slot, attrs \\ %{}) do
    parking_slot
    |> cast(attrs, [
      :parking_place,
      :loc_lat_long,
      :zone,
      :total_slots,
      :reserved_slots,
      :available_slots,
      :lock,
      :slot_buffer
    ])
    |> validate_required([
      :parking_place,
      :loc_lat_long,
      :zone,
      :total_slots,
      :reserved_slots,
      :available_slots
    ])
    |> unique_constraint(:loc_lat_long)
  end
end

lib/parkin/parking_search/pricing.ex
defmodule Parkin.ParkingSearch.Pricing do
  use Ecto.Schema
  import Ecto.Changeset

  schema "pricing" do
    field :zone, :string
    field :hourly, :integer
    field :realtime, :integer


    timestamps()
  end

  @doc false
  def changeset(pricing, attrs) do
    pricing
    |> cast(attrs, [:zone, :hourly, :realtime])
  end
end

lib/parkin_web/controllers/parkingsearch_controller.ex
defmodule ParkinWeb.ParkingsearchController do
  use ParkinWeb, :controller
  alias Parkin.Helper.Summary

  def search(conn, _params) do
    render(conn, "search.html")
  end

  def summary(conn, params) do
    keyword_searched = get_in(params, ["searchtext"])
    lat_long = Summary.get_lat_long_of_dest_address(keyword_searched)
    list_of_place_lat_long = Summary.list_of_all_lat_long()
    list_of_dest_distance = Summary.distance_between(lat_long,list_of_place_lat_long)
    res = Enum.filter(list_of_dest_distance,fn x ->
      [_zone,_location_name,avail,_total,_lat_long,distance] = x
      if avail != 0 and distance < "1.0" do x end
    end)
    case {:ok , Parkin.Helper.Summary.empty?(res)}  do

      {:ok, false} ->
        render(conn |> put_flash(:info, "Available Parking spaces"), "summary.html", query: res, keyword_searched: keyword_searched)

      {:ok, true} ->
        render(conn |> put_flash(:error, "No available Parking spaces"), "summary.html", query: res, keyword_searched: keyword_searched)
    end
  end
  @spec summary_details(Plug.Conn.t(), any) :: Plug.Conn.t()
  def summary_details(conn,params) do
    placename = get_in(params, ["placename"])
    lat_long = get_in(params, ["latlong"])
    distance = get_in(params, ["dist"])
    payment_summary = Summary.get_zone_payment_data_from(lat_long)
    render(conn |> put_flash(:info, "Parking summary"), "summarydetails.html",payment_summary: payment_summary, placename: placename, distance: distance  )
  end

  def create(conn, _params) do
    conn
    |> put_flash(:info, "Available Parking spaces")
    |> redirect(to: Routes.parkingsearch_path(conn, :search))
  end
end

lib/parkin_web/views/parkingsearch_view.ex
defmodule ParkinWeb.ParkingsearchView do
  use ParkinWeb, :view
end

lib/parkin_web/templates/parkingsearch/search.html.eex
<%= form_for @conn, Routes.parkingsearch_path(@conn, :summary),[id: "search-form"], fn f -> %>

  <div class="form-group" id="searchBoxContainer">
    <%= text_input f, :searchtext %>
  </div>
  <div id='printoutPanel'></div>
  <%= submit "Search" ,id: "submit-button" %>
<% end %>
<div id='myMap' style='width: 48vw; height: 65vh;'></div>
<script type='text/javascript'>
            function loadMapScenario() {
                var map = new Microsoft.Maps.Map(document.getElementById('myMap'), {
                    /* No need to set credentials if already passed in URL */
                    center: new Microsoft.Maps.Location(58.3708, 26.7147),
                    zoom: 12
                });
                Microsoft.Maps.loadModule(['Microsoft.Maps.AutoSuggest','Microsoft.Maps.Directions'], function () {
                    var options = {
                        maxResults: 4,
                        map: map
                    };
                    var manager = new Microsoft.Maps.AutosuggestManager(options);
                    manager.attachAutosuggest('#searchtext', '#searchBoxContainer', selectedSuggestion);

                    /*var directionsManager = new Microsoft.Maps.Directions.DirectionsManager(map);
                    directionsManager.setRequestOptions({ routeMode: Microsoft.Maps.Directions.RouteMode.transit });
                    var waypoint1 = new Microsoft.Maps.Directions.Waypoint({ address: 'Raatuse', location: new Microsoft.Maps.Location(58.38449, 26.74078) });
                    var waypoint2 = new Microsoft.Maps.Directions.Waypoint({ address: 'Veski', location: new Microsoft.Maps.Location(58.37952, 26.7097) });
                    directionsManager.addWaypoint(waypoint1);
                    directionsManager.addWaypoint(waypoint2);*/

                });
                /*Microsoft.Maps.loadModule('Microsoft.Maps.Directions', function () {
                      var directionsManager = new Microsoft.Maps.Directions.DirectionsManager(map);
                      // Set Route Mode to transit
                      directionsManager.setRequestOptions({ routeMode: Microsoft.Maps.Directions.RouteMode.transit });
                      var waypoint1 = new Microsoft.Maps.Directions.Waypoint({ address: 'Raatuse', location: new Microsoft.Maps.Location(58.38449, 26.74078) });
                      var waypoint2 = new Microsoft.Maps.Directions.Waypoint({ address: 'Veski', location: new Microsoft.Maps.Location(58.37952, 26.7097) });
                      directionsManager.addWaypoint(waypoint1);
                      directionsManager.addWaypoint(waypoint2);
                      // Set the element in which the itinerary will be rendered
                      //directionsManager.setRenderOptions({ itineraryContainer: document.getElementById('printoutPanel') });
                      //directionsManager.calculateDirections();
                  });*/
                function selectedSuggestion(suggestionResult) {
                    map.entities.clear();
                    map.setView({ bounds: suggestionResult.bestView });
                    var pushpin = new Microsoft.Maps.Pushpin(suggestionResult.location);
                    map.entities.push(pushpin);
                    document.getElementById('printoutPanel').innerHTML =
                        'Suggestion: ' + suggestionResult.formattedSuggestion +
                            '<br> Lat: ' + suggestionResult.location.latitude +
                            '<br> Lon: ' + suggestionResult.location.longitude;
                }

            }
</script>
<script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?key=Avg6Y6Q2bxNg9JmKQjKelyVssmALndKw9kZCU0ws9siu_JQb-JIsyilkLJeDH9T0&callback=loadMapScenario' async defer></script>

lib/parkin_web/templates/parkingsearch/summary.html.eex
Location searched : <%= key = @keyword_searched %>
<table class="table table-hover">
    <thead>
      <tr>
        <th>Location</th>
        <th>Zone</th>
        <th>Latitude,Longitude</th>
        <th>Distance(in K.M)</th>
        <th> Action </th>
      </tr>
    </thead>
    <tbody>
    <%= for item <- @query do %>
        <% [zone,location_name,avail,_total,lat_long,distance] = item %>
        <%= if distance < "1.0" and avail > 0 do %>
          <tr>
            <td><%= location_name %></td>
            <td><%= zone %></td>
            <td>(<%= lat_long %>)</td>
            <td><%= distance %></td>
            <td><%= link "Select #{location_name}", to: Routes.parking_path(ParkinWeb.Endpoint, :new, ["loc_lat_long": lat_long]), class: "btn btn-default" %> </td>
        </tr>

        <% end %>

    <% end %>


    </tbody>
  </table>

lib/parkin_web/templates/parkingsearch/summarydetails.html.eex
Parking Searched in area : <%=  @placename %>

<table class="table table-hover">
    <thead>
      <tr>
        <th>Location</th>
        <th>Zone</th>
        <th>Latitude,Longitude</th>
        <th>Distance(in K.M)</th>
        <th>Available slots</th>
        <th>Total slots</th>
        <th>Hourly Payment </th>
        <th>Realtime Payment </th>
      </tr>
    </thead>
    <tbody>
        <% [parking_place,loc_lat_long,zone,available_slots,total_slots,hourly,realtime] = @payment_summary %>
          <tr>
            <td><%= parking_place %></td>
            <td><%= zone %></td>
            <td>(<%= loc_lat_long %>)</td>
            <td><%= @distance %></td>
            <td><%= available_slots %></td>
            <td><%= total_slots %></td>
            <td><%= hourly %></td>
            <td><%= realtime %></td>
        </tr>
    </tbody>
  </table>